РК 1 w/ tests
go-park-mail-ru/2023_1_Technokaif pull request #2
Opened 2023-03-09 01:06 UTC by yarikTri

2023-03-09 05:16 UTC, nickeskov requested changes

2023-03-09 05:16 UTC, nickeskov commented on internal/pkg/usecase/auth.go
> +		return nil, errors.New("no such user")
Кажется сообщение ошибки не оч отражает суть происходящего. Или так было задуманно?

2023-03-09 05:16 UTC, nickeskov commented on internal/pkg/usecase/auth.go
> +	return fmt.Sprintf("%x", hashedPassword)
Это вполне ок, но есть [штука](https://pkg.go.dev/encoding/hex#EncodeToString) более предназначенная для этого и более простая

2023-03-09 05:16 UTC, nickeskov commented on internal/pkg/usecase/auth.go
> +	UserVersion uint `json:"user_version"`
Тут лучше использовать конкретные типы с чёткой битностью, а не платформеннозависимые.

2023-03-09 05:16 UTC, nickeskov commented on internal/pkg/usecase/auth_test.go
> +func TestUsecaseCheckHash(t *testing.T) {
А что этот тест проверяет? Библиотечную функцию? Зачем тестировать библиотечные функции?

2023-03-09 05:16 UTC, nickeskov commented on internal/server/server.go
> +		WriteTimeout:   10 * time.Second,
Лучше не хардкодить, а в константы хотя б

2023-03-09 05:16 UTC, nickeskov commented on internal/pkg/delivery/auth.go
> +	}
Почитал доку, там написано, что ошибка будет ток при `isValid == false`, так что мб это можно упростить.
А в ошибке содержится контекст + описание в чём была проблема? Ели да, то мб стоит её вернуть

2023-03-09 05:16 UTC, nickeskov commented on internal/pkg/delivery/auth.go
> +	if err != nil || user == nil {
Вообще, это странный кейс, что `user == nil` при `err == nil`. Такого имхо не должно быть и не надо так делать. Но в целом я свой коммент насчёт мидлвари сказал, так что, наверное, после его фикса этот issue станет не особо релевантен

2023-03-09 14:11 UTC, nickeskov approved these changes
В целом ок, но есть над чем ещё поработать.

2023-03-09 14:12 UTC, merged

2023-03-14 09:46 UTC, yarikTri commented on internal/pkg/usecase/auth.go
> +var secret = os.Getenv("SECRET")
Вот у нас есть структура Config для БД, мы хотим проверять все 6 полей в ней на пустоту. Нам стоит просто сделать 6 if-ов или через рефлект обойти?