F2 1 playlist
go-park-mail-ru/2023_1_Technokaif pull request #30
Opened 2023-04-17 19:11 UTC by yarikTri

Логика плейлистов
Пока что нет тестирования и сегодня будет загрузка обложек для плейлистов

2023-04-20 00:23 UTC, nickeskov requested changes

2023-04-20 00:23 UTC, nickeskov commented on internal/pkg/user/repository/postgresql/user_repository.go
> +		err := rows.Scan(&u.ID, &u.Username, &u.Email, &u.FirstName, &u.LastName, &u.Sex, &u.BirthDate.Time)
Интересно кст, то вы юзаете `sqlx` методы, то чисто `sql`. Оба варика жизнеспособные и вполне нормальные, прост интересно поч так?

2023-04-20 00:23 UTC, nickeskov commented on cmd/app/internal/init/router/router.go
> +							r.Post("/", playlistH.AddTrack)
Вообще, в целом, конкатенацией не оч красиво. Есть `path.Join` (именно `path`, не `filepath`, заодно и почитайте почему). Или если джоините что-то к урлу, то лучше вот [это](https://pkg.go.dev/net/url#JoinPath) юзать. В как раз в последней версии го появилось

2023-04-20 00:23 UTC, nickeskov commented on internal/pkg/user/repository/postgresql/user_repository.go
> +
Вообще, после цикла лучше всегда ещё проверять на `if err := rows.Err(); err != nil { ....}`. Вы, к примеру, при ошибке можете и не попасть внутрь цикла, т.к. `rows.Next()` вам тупо сразу `false` вернёт и всё. И ошибка останется проигноренной.

Это стоит поправить во всех местах, где такое имеется. Без исключений.

2023-04-20 00:23 UTC, nickeskov commented on internal/pkg/user/usecase/user_usecase.go
> +	}
Уже писал, норм, но лучше специализированные методы делать. И кст напоминаю, что лучше,чтобы ошибка полностью отражала контекст и содержала нужную доп. инфу
Конечно, пароли, секреты и прочуюю `sensitive data` в ошибки просто так пихать не стоит, тк они часто попадают в логи))

2023-04-20 00:23 UTC, nickeskov commented on internal/pkg/user/usecase/user_usecase.go
>  	if _, err := file.Seek(0, 0); err != nil {
Про это уже писалось, негоже так делать

2023-04-20 00:26 UTC, yarikTri commented on internal/pkg/user/repository/postgresql/user_repository.go
> +		err := rows.Scan(&u.ID, &u.Username, &u.Email, &u.FirstName, &u.LastName, &u.Sex, &u.BirthDate.Time)
BirthDate по дефолту не может быть заполнено sqlx'ом

2023-04-20 22:37 UTC, stepanpopov commented on internal/pkg/playlist/repository/postgresql/playlist_repository.go
> +		p.tables.LikedPlaylists())
"Поэтому часто вот такие данные помечают как "отмеченные для удаления" и фильтруют в итоговой выдаче." 
Это же 1 в 1 как работает постгрес, неужели стоит для оптимизации это делать на прикладном уровне?

2023-04-20 23:35 UTC, stepanpopov commented on internal/pkg/playlist/usecase/playlist_usecase.go
> +}
просто не хотел выносить специфичную для этого usecase'а ошибку в модели, а как еще лучше требовать ее от интерфейса usecase'а не придумал

2023-04-23 17:50 UTC, nickeskov requested changes

2023-04-23 17:50 UTC, nickeskov commented on internal/pkg/playlist/repository/postgresql/playlist_repository.go
> +			_ = tx.Rollback()
смысла в этом особо нету, если честно. если коммит не прошёл, то и rollback тоже вряд ли пройдёт...
да и при ошибке коммита оно вроде автоматом роллбечится

2023-04-23 17:50 UTC, nickeskov commented on internal/pkg/playlist/repository/postgresql/playlist_repository.go
> +		p.tables.LikedPlaylists())
Хммм, ну, в целом нет. Можете оставить как есть)

2023-04-23 17:50 UTC, nickeskov commented on internal/pkg/playlist/usecase/playlist_usecase.go
> +		user, err := u.userRepo.GetByID(uid)
Ну, как хотите)

2023-04-23 17:50 UTC, nickeskov commented on internal/pkg/playlist/usecase/playlist_usecase.go
> +}
Ммм
Ну, юзкейс юзер всё-таки юзает специфичный, так или иначе. И он должен понимать, какие ошибки он должен обработать
Но всё же метод, который выбрасывает константу не ок. Зачем вам этот метод? Зачем это требовать от интерфейса юзкейса? Опишите в доке, что может быть такая ошибка у такого метода и всё. Остальное это проблема юзера обработать всё корректно

2023-04-23 17:50 UTC, nickeskov commented on internal/pkg/playlist/usecase/playlist_usecase.go
> +	}
зочем? и я уже об этом говорил

2023-04-23 17:50 UTC, nickeskov commented on internal/pkg/track/delivery/http/track_delivery_models.go
> +func (t *trackCreateInput) escapeHtml() {
Кстати, go-way, если вы заметили, аббривеатуры писать большими буквами. Правильнее было бы `escapeHTML`, но это мелочь в целом (и это во всех подобных местах).

2023-04-23 17:50 UTC, nickeskov commented on internal/pkg/user/repository/postgresql/user_repository.go
> +
Вы во всех же местах поправили, да, да???

2023-04-23 17:50 UTC, nickeskov commented on internal/pkg/user/usecase/user_usecase.go
> +	return ErrAvatarWrongFormat
Про это уже писал, что в целом не хорошо так делать. Чем меньше интерфейс, тем лучше
А такие методы это, по-болшому счёту, лишний багаж

2023-04-23 20:27 UTC, yarikTri commented on internal/common/tests/delivery_http.go
> +	return fmt.Sprintf(`{"message": "%s"}`, msg)
Исключительно только в тестах

2023-04-25 11:50 UTC, nickeskov commented on internal/common/file/file_create.go
> +	}
Ну, ладно. Оставим тогда так
Но по семантике оно и правда не нужно, вы отаёте аргумент, который должен вычитаться

2023-04-25 17:13 UTC, nickeskov requested changes

2023-04-25 17:13 UTC, nickeskov commented on internal/pkg/playlist/usecase/playlist_usecase.go
> +	}
Я про такое уже писал, что лучше делать спец методы для такого. Но да ладно

2023-04-26 13:21 UTC, nickeskov requested changes

2023-04-26 13:21 UTC, nickeskov commented on internal/pkg/album/repository/postgresql/album_repository.go
> +		p.tables.Albums(), amountLimit)
Переделать на плейсхолдеры

2023-04-26 13:21 UTC, nickeskov commented on internal/pkg/artist/repository/postgresql/artist_repository.go
> +		p.tables.Artists(), amountLimit)
И тут тоже

2023-04-26 18:28 UTC, nickeskov commented
@yarikTri @stepanpopov 
Необходимо добиться прохождения команды из корня директории:
```sh
$  go vet ./... && golangci-lint run && go build -o ./build/bin/app.exe ./cmd/app/main.go && go test -race -coverprofile=atomic ./...
```

2023-04-27 09:45 UTC, nickeskov approved these changes

2023-04-27 09:45 UTC, merged