F2 2 microservices
go-park-mail-ru/2023_1_Technokaif pull request #34
Opened 2023-04-23 23:35 UTC by yarikTri

Auth microservice implemented

2023-04-26 15:13 UTC, nickeskov requested changes
Есть что править, особенно с непонятными мувами с агентами + грпц.

2023-04-26 15:13 UTC, nickeskov commented on internal/pkg/auth/client/grpc/auth_agent.go
Вы выпилили весь юзкейс, зачем-то сделали его обёрткой. Логики юзкейса я чёт найти не могу, вопрос, что тогда делает юзкейс, зачем эта обёртка? А правильнее сказать, зачем агент? Почему нельзя просто было реализовать юзкейс с подкапотным хождением по грпц?
Думаю другие агенты вы хотели делать также, так что призадумайтесь, а надо ли оно вам?

2023-04-26 15:13 UTC, nickeskov commented on internal/pkg/auth/microservice/grpc/service/auth_service.go
Вы должны были переиспользовать старый юзкейс тут, а вы по факту запихнули всю логику юзкейса в слой представления да и ещё бахнули так, что оно теперь полностью завязано на грпц
Надо будет переделать. Я рассматриваю это как фатальный недостаток

2023-04-26 15:13 UTC, nickeskov commented on cmd/api/init/app/init.go
Кстати, а что за `api`? Это типа сервис новый?

2023-04-26 15:13 UTC, nickeskov commented on cmd/api/init/app/init.go
> +	grpcAuthConn, err := grpc.Dial(os.Getenv(cmd.AuthHostParam)+":"+os.Getenv(cmd.AuthPortParam),
Кмк лучше былоб сделать переменную среды, которая сразу бы в себе содержала нужный эндпоинт (т.е. хост + порт)
И про размазывание логики я уже вроде говорил. Но это на ваше усморение)

2023-05-02 11:51 UTC, stepanpopov commented on internal/pkg/auth/client/grpc/auth_agent.go
> +			}
теперь для ошибок, для которых не требуется врапить нашу внутреннюю ошибку, возвращаем просто err, это происходит в строчке ниже switch case'а

2023-05-02 11:56 UTC, stepanpopov commented on cmd/api/init/app/init.go
это main, там роутер и для микросервисов как клиент

2023-05-03 04:50 UTC, nickeskov requested changes

2023-05-03 04:50 UTC, nickeskov commented on internal/pkg/microservices/search/delivery/grpc/search_delivery.go
> +			UserID:    nilCheckUint32(artist.UserID),
Вообще, если что, в протобафе тоже есть nullable типы. И если не ошибаюсь, в протобафе есть optional поля.

2023-05-03 04:50 UTC, nickeskov commented on internal/pkg/search/client/grpc/search_agent.go
> +		}
`errors.Is`

2023-05-03 04:50 UTC, nickeskov commented on internal/pkg/search/client/grpc/search_agent.go
> +	defer cancel()
К слову, для доп инфы вы можете юзать с `go1.20` такую штуку как `context.WithCancelCause`. Почитайте, иногда полезно бывает.

Но тут кст вы ничего раньше времени не собираетесь отменять, так что для чего тут такое не оч понятно (если под капот глянете, то там всё-таки немалая машинерия происходит, даже горутинка может создаться).
Но, иногда, если вы где-то накосячили с явным освобождением ресурсов это может вас спасти, но далеко не всегда, и то если создатели либы/ваш код предусматривает очистку ресурсов при отмене контекста (если они ещё не были почищены).

2023-05-03 04:50 UTC, nickeskov commented on internal/pkg/microservices/user/delivery/grpc/user_delivery.go
> +				return status.Error(codes.InvalidArgument, "got invalid file chunk")
Думаю тут можно смело `Internal` ставить, тк запись сырых байт в `bytes.Buffer` не может просто так зафейлиться

2023-05-03 04:50 UTC, nickeskov commented on internal/pkg/microservices/user/delivery/grpc/user_delivery.go
> +				return status.Error(codes.InvalidArgument, "extra message transfered double")
Как другая сторона поймёт, что ну чего-то не так, что она что-то не так сделала? Или другая сторона тупо повиснет?

2023-05-03 04:50 UTC, nickeskov commented on internal/pkg/microservices/user/delivery/grpc/user_delivery.go
> +		}
Как другая сторона поймёт, что ну чего-то не так, что она что-то не так сделала? Или другая сторона тупо повиснет?

2023-05-03 04:50 UTC, nickeskov commented on internal/pkg/microservices/user/delivery/grpc/user_delivery.go
> +	usecaseInput.file = bytes.NewReader(buffer.Bytes())
У вас `bytes.Buffer` и так реализует `io.Reader`, если я не ошибаюсь. Но это конечно тоже беспроигрышный  вариант

2023-05-03 04:50 UTC, nickeskov commented on internal/pkg/microservices/user/delivery/grpc/user_delivery.go
> +	}
Ой опасненько так делать. `gosec` за такое ой как ругается. Почитайте про [вот это ](https://stackoverflow.com/questions/62446118/implicit-memory-aliasing-in-for-loop).

2023-05-03 04:50 UTC, nickeskov commented on internal/pkg/microservices/proto/common.proto
> +}
Выровняйте поля плз, глаз режет

2023-05-03 04:50 UTC, nickeskov commented on internal/pkg/microservices/proto/gen.go
Тоже пойдёт, но не очень очевидно. Я бы ещё добавил отдельный таргет в мейкфайле, который вам протобаф билдит. Ну в вашем случае он вызывает `go generate` для конкретного фалика.

2023-05-03 04:50 UTC, nickeskov commented on internal/pkg/microservices/proto/search.proto
> +    uint32 albumID = 3;
И тут мы тоже не забываем про выравнивание

2023-05-03 04:50 UTC, nickeskov commented on internal/pkg/microservices/proto/user.proto
> +	rpc UpdateInfo(UpdateInfoMsg) returns (UpdateInfoResponse) {};
И тут не забываем про выравнивание

2023-05-03 12:47 UTC, nickeskov approved these changes

2023-05-03 12:47 UTC, nickeskov commented
Есть ещё что править, однако многое уже не критично

2023-05-03 12:49 UTC, merged