F2 4 metrics
go-park-mail-ru/2023_1_Technokaif pull request #38
Opened 2023-05-04 06:35 UTC by stepanpopov

2023-05-08 19:11 UTC, nickeskov requested changes

2023-05-08 19:11 UTC, nickeskov commented on internal/common/http/middleware/metrics.go
> +				code := commonHTTP.GetResponseCodeFromRequest(r)
Зачем таку сложно? Мне кажется лучшим подходом было бы создать реализацию `http.ResponseWriter` и оборачивать в него переданный в мидлварю экземпляр. Так вы бы решили проблему без дополнительных свистоплясок и явных вызовов функций (по типу такого `*r = *WrapWithCode(r, code)`), в которые вы пишете коды ответов. 
Но правда не стоит забывать, что в такой реализации код может быть и не выставлен явно (т.е. будет дефолтное значение == 0), но такое возможно только при ответе `200 OK`

2023-05-08 19:11 UTC, nickeskov commented on docker-compose.yml
> +      - "9100:9100"
Вы хоть и в компоузе всё запускаете, но учитываете, что такая тема будет только на линухе работать (. Мне кажется это стоит как-то явно сказать.

2023-05-08 19:11 UTC, nickeskov commented on internal/common/http/middleware/metrics.go
> +				routePattern := chi.RouteContext(r.Context()).RoutePattern()
А если паттерн не нашёлся? Как вы сообщите об этом в метриках? (Конечно уж очень придиристо, но всё же)
И к слову, это можно вытащить до `start := time.Now()`. Мелочь правда тоже, но всё же

2023-05-08 19:11 UTC, nickeskov commented on internal/common/http/wrapping.go
> +type ContextKeyResponseCodeType struct{}
А оно точно вам нужно как публичный тип? Мб можно это как-то сделать приватным?

2023-05-08 19:11 UTC, nickeskov commented on internal/pkg/microservices/auth/delivery/grpc/auth_delivery.go
> +		Sex:       models.Male,
Вроде это ж вы хотели выпилить? Это сделано уже в след PR? Если да, то ок. Если нет, то жду. Либо отпишитесь, чего как у вас по этому

2023-05-11 22:23 UTC, nickeskov requested changes

2023-05-11 22:23 UTC, nickeskov commented on internal/common/http/middleware/metrics.go
> +}
Советую написать тесты и проверить, а будет ли оно вообще работать или нет.

2023-05-11 22:23 UTC, nickeskov commented on internal/pkg/microservices/auth/delivery/grpc/auth_delivery.go
> +		Sex:       models.Male,
Какой статус то?

2023-05-11 22:24 UTC, nickeskov commented on docker-compose.yml
> +      - "9100:9100"
Хотя бы коммент добавить...

2023-05-14 20:14 UTC, stepanpopov commented on internal/pkg/microservices/auth/delivery/grpc/auth_delivery.go
> +		Sex:       models.Male,
выпилим в следующих ветках, уже начали

2023-05-15 09:02 UTC, nickeskov approved these changes

2023-05-15 09:02 UTC, merged