F1-2: Done architecture (RK 2 w/o security & tests)
go-park-mail-ru/2023_1_Technokaif pull request #7
Opened 2023-03-21 22:38 UTC by yarikTri

2023-03-23 18:57 UTC, nickeskov requested changes

2023-03-23 18:57 UTC, nickeskov commented on internal/pkg/album/repository/postgresql/album_repository.go
> +
Роллбек или коммит стоит делать через `defer`.  А если вы забудете где-то сделать коммит или ролбек в каком-то из if/else? Да и не показалось ли вам странным, что столько много копипасты получается?
```go
func foo() (_ int, err error) {
	// ...
	defer func() {
		if err != nil {
			// rollback
		} else {
			// commit
		}
	}()
	// ...
}
````

2023-03-23 18:57 UTC, nickeskov commented on internal/pkg/album/usecase/album_usecase.go
> +
А если в модели альбома каша содержится? @yarikTri помнишь говорили, что каждый домен должен отвечать за свои проверки на своём уровне?

2023-03-23 18:57 UTC, nickeskov commented on internal/pkg/artist/delivery/http/artist_delivery.go
> +	// ...
whut?

2023-03-23 18:57 UTC, nickeskov commented on internal/pkg/track/delivery/http/track_delivery.go
> +	// ...
Whut?

2023-03-23 18:57 UTC, nickeskov commented on internal/pkg/user/repository/postgresql/user_repository.go
> +				COALESCE(avatar_src, '')
Зачем `COALESCE` тут?

2023-03-23 18:57 UTC, nickeskov commented on internal/pkg/user/delivery/http/user_delivery.go
> +func (h *Handler) Read(w http.ResponseWriter, r *http.Request) {
Какой-то странный нейминг..

2023-03-23 18:57 UTC, nickeskov commented on internal/pkg/track/usecase/track_usecase.go
> +	}
Как-то сложно, лучше выделить в отдельный метод. Да и как-то это не изолированно. По-хорошему тут всё должно быть внутри транзакции

2023-03-23 18:57 UTC, nickeskov commented on internal/pkg/track/repository/postgresql/track_repository.go
> +		tx.Rollback()
defer

2023-03-23 18:57 UTC, nickeskov commented on cmd/app/internal/init/router/router.go
> +			r.Route("/{albumID}", func(r chi.Router) {
Видел константы для этого. Почему бы их тоже тут не заюзать?

2023-04-07 01:12 UTC, nickeskov requested changes

2023-04-07 19:34 UTC, yarikTri commented on internal/pkg/track/delivery/http/track_delivery.go
> +	user, _ := commonHttp.GetUserFromRequest(r)
Ошибка здесь обозначает, что юзер не авторизован
Есть ручки (например эта), в которых нам не важна авторизация. То есть, если её нет, то юзер будет nil, передадим его в следующую функцию и она отработает правильно.

2023-04-07 19:39 UTC, nickeskov commented on internal/pkg/track/delivery/http/track_delivery.go
> +	user, _ := commonHttp.GetUserFromRequest(r)
Это пока так
а если потом она поменяется и добавится сериализация/десериализация?
как ты поймёшь, что это была именно авторизация?
что всё ок, и юзер тупо не авторизован, а не что-то другое?

2023-04-07 19:44 UTC, yarikTri commented on internal/pkg/user/delivery/http/user_delivery_models.go
> +func (ui *userInfoInput) ToUser(user *models.User) *models.User {
Неа, это в принципе для апдейта юзера, в том числе аватара

2023-04-07 19:47 UTC, yarikTri commented on internal/pkg/track/usecase/track_usecase.go
> +	iSdeleted, err := u.trackRepo.DeleteLike(trackID, userID)
Задаём тренд всему комьюнити
попоВкузьмиНкейС

2023-04-07 19:48 UTC, yarikTri commented on internal/pkg/track/repository/postgresql/track_repository.go
> +		WHERE at.artist_id = $1;`,
Не первый раз говоришь)
Помню, просто я душнила

2023-04-07 19:49 UTC, yarikTri commented on internal/pkg/track/repository/postgresql/track_repository.go
> +	if deleted == 0 {
Ahahahah, so funny

2023-04-07 19:52 UTC, yarikTri commented on internal/pkg/track/delivery/http/track_delivery.go
> +		tlr.Status = "already liked"
Мы считаем нормальным сценарием пытаться с точки зрения АПИ попытаться лайкнуть что-то, что уже лайкнуто. Ответ будет не типа "Жесть, нельзя, было уже, вот тебе 400", а типа "ТВой лайк уже засчитан, зачилься, дружище"

2023-04-07 19:58 UTC, yarikTri commented on internal/common/http/responces.go
> +		}
Это код статуса, а не длина сообщения

2023-04-07 20:01 UTC, yarikTri commented on internal/common/file_validation.go
> +	fmt.Println()
Жёсткий дебаг походу

2023-04-07 20:22 UTC, yarikTri commented on internal/pkg/auth/usecase/auth_usecase.go
> +	if err := u.authRepo.UpdatePassword(userID, passHash, fmt.Sprintf("%x", salt)); err != nil {
Помню, что при дебаге долго что-то не выкупали и пришли к такому решению

2023-04-08 12:25 UTC, nickeskov commented on internal/pkg/track/delivery/http/track_delivery.go
> +		tlr.Status = "already liked"
А фронт как будет понимать, что уже лайкнуто? У вас вот эти статусы определены в общем API? Специфицированы?

2023-04-08 12:27 UTC, nickeskov commented on internal/common/http/responces.go
Кстати, правильно `responses` (я про имя файла)

2023-04-08 12:27 UTC, nickeskov commented on internal/common/http/responces.go
> +		}
Хмм, действительно, убедил)

2023-04-08 22:50 UTC, yarikTri commented on internal/pkg/track/delivery/http/track_delivery.go
> +		tlr.Status = "already liked"
Тогда, чтобы в сваггер занеслось, надо сделать "енам" тип, где перечислить ответы
Должно работать, если я не ошибаюсь

2023-04-11 19:25 UTC, nickeskov commented on cmd/app/main.go
> +}
newline

2023-04-11 20:33 UTC, nickeskov requested changes

2023-04-11 20:33 UTC, nickeskov commented on internal/common/folgers.go
> +	var dirForUserAvatars = mediaPath + avatarsFolder
`filepath`

2023-04-11 20:33 UTC, nickeskov commented on internal/common/folgers.go
> +	var dirForTracks = mediaPath + recordsFolder
`filepath`

2023-04-11 20:33 UTC, nickeskov commented on internal/common/http/get_from_request.go
> +	id, err := strconv.ParseUint(idUrl, 10, 0)
Почему последний параметр 0? Последний параметр тут это количество бит числа. У вас 0 бит?
Хотя 0, как я понял, это означает битность типа `int`, но вы всё равно 32 бита ождаете.

2023-04-11 20:33 UTC, nickeskov commented on internal/common/http/middleware/panic.go
> +					logger.Errorf("PANIC (recovered): %s", err)
Обычно ещё стоит стектрейс сохранять, чтобы понять, где паника то возникла. Прогуглите, это можн сделать вполне

2023-04-11 20:33 UTC, nickeskov commented on internal/common/http/responses.go
> +		w.Write([]byte(`{"message": "can't encode error response into json, msg: ` + msg + `"}`))
Вообще, в `msg` могут содержаться символы типа `\n`, '\t' которые в JSON преобразуются в текст "\n\t"
Тут они просто будут отобраться как перенос строки и таб соотв., что будет ломать JSON вроде как
Но это тож можно обработать, вроде как

2023-04-11 20:33 UTC, nickeskov commented on internal/pkg/track/usecase/track_usecase.go
> +			userInArtists = true
Всё ещё актуально

2023-04-11 20:33 UTC, nickeskov commented on internal/pkg/user/delivery/http/middleware/user_middleware.go
> +}
newline

2023-04-11 20:33 UTC, nickeskov commented on internal/pkg/user/usecase/user_usecase.go
> +var dirForUserAvatar = common.MediaPath() + common.AvatarFolder()
`filepath.Join`

2023-04-11 20:33 UTC, nickeskov commented on internal/pkg/user/usecase/user_usecase.go
> +	filenameWithExtencion := newFileName + "." + fileExtension
Extension

2023-04-11 20:33 UTC, nickeskov commented on internal/pkg/user/usecase/user_usecase.go
> +		newFD, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE, 0666)
Я думаю можно и `0666` вполне оставить, но чем более низкие права доступа, тем лучше :)
Поэтому лучше было бы `0600`, хотя зависит от вашей логики, один юзер должен иметь доступ к файлам или несколько.

2023-04-11 20:44 UTC, yarikTri commented on internal/common/http/get_from_request.go
> +	id, err := strconv.ParseUint(idUrl, 10, 0)
Меня внутрення реализация Atoi сбила
![image](https://user-images.githubusercontent.com/91901091/231283913-e65aa4f0-1291-4af6-a58a-a894927e35fa.png)

2023-04-11 20:55 UTC, nickeskov commented on internal/common/http/middleware/panic.go
> +					logger.Errorf("PANIC (recovered): %s", err)
https://stackoverflow.com/questions/52103182/how-to-get-the-stacktrace-of-a-panic-and-store-as-a-variable

2023-04-11 20:58 UTC, yarikTri commented on internal/pkg/user/usecase/user_usecase.go
> +	filenameWithExtencion := newFileName + "." + fileExtension
filepath.Ext?

2023-04-11 21:51 UTC, nickeskov commented on internal/pkg/user/usecase/user_usecase.go
> +	filenameWithExtencion := newFileName + "." + fileExtension
я имел ввиду, что опечатка тут)
Но ладн)

2023-04-11 22:01 UTC, nickeskov requested changes

2023-04-11 22:01 UTC, nickeskov commented on internal/common/file_validation.go
> +	}
Зачем этот seek?
Пусть пользователь сам возвращает в начале, если ему надо. Это его отвественность, не функции

2023-04-11 22:11 UTC, nickeskov commented on internal/common/http/responses.go
> +		w.Write([]byte(`{"message": "can't encode error response into json, msg: ` + msg + `"}`))
ещё актуальненько

2023-04-11 22:12 UTC, nickeskov requested changes

2023-04-11 22:13 UTC, nickeskov commented on internal/pkg/track/repository/postgresql/track_repository.go
> +		tx.Rollback()
ку-кс

2023-04-11 23:57 UTC, nickeskov approved these changes

2023-04-11 23:59 UTC, merged